### ISSUE TITLE
Bretonnian crusade fails turn after spawn

### ISSUE THREAD

**Issue by Jolc3r** [Frodo45127/tww3_dynamic_disasters#1]
Bretonian mid-game crusade fails the turn after spawn (dyn_dis_bretonain_crusades_bad_end). Effect is still active on spawned armies.

Mods used (mod list from the mod manager):
2854131314|2859968660|2869552176|2789887182|2885767563|2949216752|2790197553|2922534576|2789858755|2795542235|2789853654|2810936088|2907466537|2790055541|2789854789|2918137037|2914599323|2914955087|2935815665|2926849712|2927235297|2915203772|2933549532|2961852689|2789921931|2789878031|2853433455|2864811951|2790490527|2877071147|2886173394|2926733791|2809686435|2789857593|2789906398|2789896451|2854849373|2856219244|2853474600|2878565209|2853069797|2843420163|2927955021|2867163312|2858804223|2853974146|2806090102|2860018514|2806090945|2860741213|2806052263|2793127003|2789857945|2791465729|2858832821|2857612635|2861006090|2794064207|2791241084|2790774407|2859802328|2854219972|2961085509|2789865816|2792727547|2943940309|2853228292|2857954773|2856679508|2862340751|2853029812

Log here
[script_log_210423_0132_backup_dynamic_disaster_log.txt](https://github.com/Frodo45127/tww3_dynamic_disasters/files/11293141/script_log_210423_0132_backup_dynamic_disaster_log.txt)

**Comment by Frodo45127** [comment]
how much time passed between you getting the warning about the invasion and the invasion happening? Just found a bug that caused the time between warning and invasion to be counted as "crusading time", so in certain situations, armies would get released way sooner that expected, causing the disaster to fail early.

**Comment by Jolc3r** [comment]
It was about 7 turns I think, not sure. I don't know if I have a save before it triggered.

**Comment by Frodo45127** [comment]
Will close the issue for now, as I don't see more related bugs. If it triggers again, feel free to reopen this issue.
